node {
stage ('Git Checkout'){
git "https://github.com/Kiranmaiadams/CBE-Automation"
//sh script:"echo Checking code from", label: env.BRANCH_NAME
}
stage ('Build Project'){
bat "mvn -f StayBeta/pom.xml clean"
}
 stage ('Run Test'){
bat "mvn -f StayBeta/pom.xml test"
}

stage ('Publish Report'){
publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: 'StayBeta/Reports/', reportFiles: '1SourceReleaseReport.html', reportName: '1SourceReleaseReport', reportTitles: ''])
publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: 'StayBeta/target/', reportFiles: 'cucumber-results-feature-overview.html', reportName: 'CucumberHTML', reportTitles: ''])

cucumber failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: 'cucumber.json', jsonReportDirectory: 'StayBeta/target/cucumber-reports/', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
}


 stage('Email Notification') 
 {
                bat "del Reports.zip"
                echo "ZIP"
               zip zipFile: 'Reports.zip', archive: false, dir: 'C:/Program Files (x86)/Jenkins/workspace/CBE StayBeta Pipeline/StayBeta/Reports'
               echo "END - ZIP"
               emailext attachmentsPattern: 'Reports.zip', body: '${SCRIPT,template="allure-report.groovy"}', 
                subject: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - Successful", 
                    mimeType: 'text/html',to: "qateam@statravel.com"
           
        }
    }
   