node {
properties([parameters([choice(choices: ['TestExecutionFiles/HotelBookQuote.xml', 'TestExecutionFiles/HotelAmendments.xml', 'TestExecutionFiles/InsuranceBookAndCancel.xml', , 'TestExecutionFiles/TransfersBookandCancel.xml'], description: 'Select Which Test Suite You Want to Run', name: 'TestsToRun')])])
stage ('Git Checkout'){
git "https://github.com/STA-QA/CBE-StayBeta"
//sh script:"echo Checking code from", label: env.BRANCH_NAME
}
stage ('Build Project'){
echo "Cleaning"
bat "mvn -f StayBeta/pom.xml clean"
echo "CleaningCompleted"
}
stage ('Run Test'){
echo "tests"
bat "mvn -f StayBeta/pom.xml test -Dsurefire.suiteXmlFiles=${TestsToRun}"
}

stage ('Publish Report'){
publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: 'StayBeta/Reports/', reportFiles: '1SourceReleaseReport.html', reportName: '1SourceReleaseReport', reportTitles: ''])
publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: 'StayBeta/target/', reportFiles: 'cucumber-results-feature-overview.html', reportName: 'CucumberHTML', reportTitles: ''])

cucumber failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: 'cucumber.json', jsonReportDirectory: 'StayBeta/target/cucumber-reports/', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
}


 stage('Email Notification') 
 {
                bat del "StayBeta/Reports.zip"
                echo "ZIP"
               zip zipFile: 'Reports.zip', archive: false, dir: 'C:/Program Files (x86)/Jenkins/workspace/new pipeline/StayBeta/Reports'
               echo "END - ZIP"
               emailext attachmentsPattern: 'Reports.zip', body: '${FILE,path="StayBeta/target/cucumber-results-feature-overview.html"}', 
                subject: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - Successful", 
                    mimeType: 'text/html',to: "qateam@statravel.com"
           
        }
    }
   